[workspace]
members = ["kaba", "kabac", "kabart_p"]
resolver = "2"

[workspace.package]
version = "0.5.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Hafidh Muqsithanova Sukarno <hafidhmn@gmail.com>"]
rust-version = "1.81"
