[package]
name = "compiler"
description = "The compiler of Kaba programming language"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
colored = "2.1.0"
indoc = "2.0.4"
logos = "0.13.0"
