[package]
name = "compiler"
description = "Compiler for Kaba programming language"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
builtin = { path = "../builtin" }
colored = "2.1.0"
indoc = "2.0.4"
logos = "0.13.0"
