[package]
name = "builtin"
description = "Built-in components of Kaba programming language implementation"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
