[package]
name = "kaba2js"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
kabac = { path = "../kabac" }

[dev-dependencies]
indoc = "2.0.4"
