[package]
name = "kaba2js"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
kabac = { path = "../kabac" }
wasm-bindgen = "0.2"

[dev-dependencies]
indoc = "2.0.4"
