name: Test

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: rustup show

    - name: rustfmt check
      run: cargo fmt --check

    - name: clippy check
      run: cargo clippy -- -Dwarnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --workspace --verbose
